import { PERMISSIONS } from "./permissions.js";

export const PERMISSION_GROUPS = Object.freeze({

  AUTH_BASIC: [
    PERMISSIONS.VER_PERFIL,
    PERMISSIONS.EDITAR_PERFIL,
    PERMISSIONS.GERENCIAR_SESSOES
  ],

  CLIENTE_BASICO: [
    PERMISSIONS.VER_CARDAPIO,
    PERMISSIONS.CRIAR_PEDIDO,
    PERMISSIONS.VER_STATUS_PEDIDO,
    PERMISSIONS.VER_HISTORICO_PEDIDOS,
    PERMISSIONS.GERENCIAR_ENDERECOS,
    PERMISSIONS.GERENCIAR_PAGAMENTOS,
    PERMISSIONS.GERENCIAR_FAVORITOS,
    PERMISSIONS.AVALIAR_PEDIDO
  ],

  ATENDIMENTO: [
    PERMISSIONS.VER_PEDIDOS,
    PERMISSIONS.ATUALIZAR_STATUS_PEDIDO,
    PERMISSIONS.ATRIBUIR_MESA,
    PERMISSIONS.CRIAR_PEDIDO_MESA,
    PERMISSIONS.FECHAR_CONTA,
    PERMISSIONS.GERENCIAR_RESERVAS
  ],

  COZINHA: [
    PERMISSIONS.VER_FILA_COZINHA,
    PERMISSIONS.FINALIZAR_PREPARO
  ],

  ESTOQUE: [
    PERMISSIONS.VER_ESTOQUE,
    PERMISSIONS.ATUALIZAR_ESTOQUE
  ],

  CAIXA: [
    PERMISSIONS.ABRIR_CAIXA,
    PERMISSIONS.FECHAR_CAIXA,
    PERMISSIONS.REGISTRAR_PAGAMENTO,
    PERMISSIONS.VER_RELATORIOS
  ],

  ADMIN_BASICO: [
    PERMISSIONS.GERENCIAR_FUNCIONARIOS,
    PERMISSIONS.GERENCIAR_CARDAPIO,
    PERMISSIONS.GERENCIAR_FILIAIS
  ],

  SUPER_ADMIN: [
    PERMISSIONS.ADMIN
  ]

});
