// config/roles.js
import { PERMISSIONS } from "./permissions.js";

export const ROLES = Object.freeze({

    CLIENTE: [
        PERMISSIONS.LOGIN,
        PERMISSIONS.VER_CARDAPIO,
        PERMISSIONS.CRIAR_PEDIDO,
        PERMISSIONS.CANCELAR_PEDIDO,
        PERMISSIONS.AVALIAR_PEDIDO
    ],

    ATENDENTE: [
        PERMISSIONS.LOGIN,
        PERMISSIONS.VER_PEDIDOS,
        PERMISSIONS.ATUALIZAR_STATUS_PEDIDO,
        PERMISSIONS.ATRIBUIR_MESA
    ],

    COZINHA: [
        PERMISSIONS.LOGIN,
        PERMISSIONS.VER_FILA_COZINHA,
        PERMISSIONS.FINALIZAR_PREPARO
    ],

    CAIXA: [
        PERMISSIONS.LOGIN,
        PERMISSIONS.ABRIR_CAIXA,
        PERMISSIONS.FECHAR_CAIXA,
        PERMISSIONS.REGISTRAR_PAGAMENTO
    ],

    GERENTE: [
        PERMISSIONS.LOGIN,
        PERMISSIONS.VER_RELATORIOS,
        PERMISSIONS.GERENCIAR_ESTOQUE,
        PERMISSIONS.GERENCIAR_FUNCIONARIOS
    ],

    ADMIN: Object.values(PERMISSIONS)
});
